name: publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - run: echo "*** npm publish --access public --tag latest ***"
        if: github.event.release.target_commitish == 'main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: echo "*** npm publish --access public --tag next ***"
        if: github.event.release.target_commitish == 'develop'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://npm.pkg.github.com
          scope: '@fastcampus'
      - run: echo "*** npm publish --tag latest ***"
        if: github.event.release.target_commitish == 'main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_NPM_TOKEN }}
      - run: echo "*** npm publish --tag next ***"
        if: github.event.release.target_commitish == 'develop'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_NPM_TOKEN }}
